apiVersion: batch/v1
kind: CronJob
metadata:
  name: minion-broken-link-recrawl
spec:
  concurrencyPolicy: Allow
  schedule: {{ .Values.schedule }}
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        metadata:
          name: minion-broken-link-recrawl
          labels:
            cron: minion-broken-link-recrawl
        spec:
          {{- include "magda.imagePullSecrets" (dict "image" .Values.cronJobImage) | indent 10 }}
          containers:
          - name: minion-broken-link-recrawl
            image: {{ include "magda.image" (dict "image" .Values.cronJobImage) | quote }}
            imagePullPolicy: {{ include "magda.imagePullPolicy" (dict "image" .Values.cronJobImage) | quote }}
            command:
              - "/bin/sh"
              - "-c"
              - "apk add --no-cache ca-certificates curl && curl -i -X POST http://minion-broken-link/recrawl"
          restartPolicy: OnFailure
