global:
  image: {}
  rollingUpdate: {}
  minions:
    image: {}

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.global.minions.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)

image: 
  name: "magda-minion-broken-link"
  # repository: 
  # pullPolicy: 
  # imagePullSecret: 

cronJobImage: 
  name: "alpine"
  repository: "docker.io"
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets: false

defaultImage:
  repository: ghcr.io/magda-io
  pullPolicy: IfNotPresent
  imagePullSecret: false

schedule: "0 0 14,28 * *"

defaultAdminUserId: "00000000-0000-4000-8000-000000000000"

# -- The base URL of the storage API to use when generating access URLs for MAGDA internal stored resources.
storageApiBaseUrl: "http://storage-api/v0"

# -- The name of the storage bucket where all dataset files are stored. 
# Should match storage API config.
# By default, it will use the value of `global.defaultDatasetBucket` (defined in `magda-core` chart) unless you specify a different value here.
datasetBucketName: ""

# Setup Domain Wait Time
# domainWaitTimeConfig:
#   data.csiro.au: 5
#   data.gov.au: 5
#   data.act.gov.au: 30

resources:
  requests:
    cpu: 50m
    memory: 40Mi
  limits:
    cpu: 200m