global:
  image: {}
  rollingUpdate: {}
  minions:
    image: {}

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.global.minions.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)

image: 
  name: "magda-minion-broken-link"
  # repository: 
  # pullPolicy: 
  # imagePullSecret: 

cronJobImage: 
  name: "alpine"
  repository: "docker.io"
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets: false

defaultImage:
  repository: docker.io/data61
  pullPolicy: IfNotPresent
  imagePullSecret: false

schedule: "0 0 14,28 * *"

defaultAdminUserId: "00000000-0000-4000-8000-000000000000"

# Setup Domain Wait Time
# domainWaitTimeConfig:
#   data.csiro.au: 5
#   data.gov.au: 5
#   data.act.gov.au: 30

resources:
  requests:
    cpu: 50m
    memory: 40Mi
  limits:
    cpu: 200m